sudo: false
os:
  - linux
  - osx
  - windows
dist: xenial
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust:
      - beta
      - nightly
  fast_finish: true
install:
  - rustup component add clippy rustfmt
script:
  - cargo clippy --benches --tests
  - cargo test
  - cargo doc
  - cargo fmt --all -- --check
